### ISSUE TITLE
Remove mutable_args restriction in get_model API 

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#1129]
I think we can remove the check of `mutable_args` in the get_model API for BERT, GPT, Language model and transformer. We can introduce a separate flag "allow_override" if users want to override any configuration. Otherwise overriding any configuration is forbidden.

**Comment by mkartik** [comment]
Hi @eric-haibin-lin, can I take this issue?

**Comment by eric-haibin-lin** [comment]
Contribution is welcome!

**Comment by ma-hei** [comment]
Hey @eric-haibin-lin,
just to clarify:
currently the mutable_args of the BERT model for example are ['use_residual', 'dropout', 'embed_dropout', 'word_embed']. Non mutable arguments of the bert_12_768_12 model are for example 'hidden_size', 'num_heads' or 'num_layers' (from looking at bert_12_768_12_hparams in model/bert.py). The goal of this fix is to allow calling nlp.model.get_model for example as follows:
`nlp.model.get_model('bert_12_768_12', dataset_name='book_corpus_wiki_en_uncased', use_classifier=False, use_decoder=False, allow_override=True, num_heads=13);`
So instead of allowing the user to modify only the parameters in mutable_args, we allow the user to modify any parameter in bert_12_768_12_hparams as long as he passes in the parameter use allow_override=True. Is this correct?

**Comment by eric-haibin-lin** [comment]
yes

**Comment by ma-hei** [comment]
@eric-haibin-lin I created a PR for this: https://github.com/dmlc/gluon-nlp/pull/1207
I asked a question in that PR. Also found the Jenkins test to be failing for what seems to be unrelated to the codebase. Would appreciate any feedback to get started with this codebase. Thanks!
