### ISSUE TITLE
Reshape argument issues in running attention cells

### ISSUE THREAD

**Issue by rishita** [dmlc/gluon-nlp#242]
```
a = mx.nd.array([[1,2,3],[2,3,4]])
print(mx.nd.reshape(a, shape=(3,2), reverse=True))
print(a.reshape(shape=(3,2), reverse=True))
```

The first one works, the second one says `"TypeError: Only 'shape' is supported as keyword argument. Got: shape, reverse."
`
Versions (latest):
gluonnlp.__version__ = '0.3.3post1'
mxnet.__version__ = '1.2.1'

Originally hitting this issue in the attention_cell code in gluonnlp, reproduced it in the aforementioned toy example based on that. 

Original exception thrown at:
```
~/anaconda3/envs/mxnet_latest_p36/lib/python3.6/site-packages/gluonnlp/model/attention_cell.py in _compute_weight(self, F, query, key, mask)
    250         query = F.transpose(query.reshape(shape=(0, 0, self._num_heads, -1)),
    251                             axes=(0, 2, 1, 3))\
--> 252                  .reshape(shape=(-1, 0, 0), reverse=True)
```

**Comment by szha** [comment]
The reverse argument in ndarray's fluent reshape was already fixed in mxnet but wasn't included in 1.2.1 release. https://github.com/apache/incubator-mxnet/blame/master/python/mxnet/ndarray/ndarray.py#L1049-L1053

Currently our CI tests for the following version: https://github.com/dmlc/gluon-nlp/blob/master/env/py3.yml#L14
