### ISSUE TITLE
[BERT] [Dataset] Renaming wiki_multilingual and wiki_cn dataset

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#491]
I am thinking of renaming `wiki_multilingual`/`wiki_cn` to `wiki_multilingual_uncased`/`wiki_cn_cased`. 

The issue is that currently creating the tokenizer requires the "do_lower_case" boolean. Users need to set that manually. It would be more consistent to rename the dataset with cased/uncased explicitly to guide users. 

With this user can set `do_lower_case='uncased' in dataset_name`.

What do you think?
@fierceX @haven-jeon @kenjewu

**Comment by kenjewu** [comment]
I think using cased / uncased to rename data sets is much clearer and easier to understand.  If I am a newcomer to `gluonnlp` or I am not familiar with these datasets,  I may not sure whether it have been cased when I got the data from gluonnlp. But if  indicate their name explicitly , anyone can understand it. 

Although it is not essential to know whether the data is lowercase when using the tokerizer, because even if the data is already lowercase, and the `do_lower_case` is set to True, program will not go wrong. But we should work hard to make the program and documentation clearer and more intuitive. Because someone may has a requirement to know  whether the data is lowercase.  Moreover, I have seen ‘book_corpus_wiki_en_cased’, ‘book_corpus_wiki_en_uncased’ in the introdcution of [gluonnlp.model.bert_12_768_12](http://gluon-nlp.mxnet.io/api/modules/model.html#gluonnlp.model.bert_12_768_12), so we should be consistent with it.

**Comment by eric-haibin-lin** [comment]
@kenjewu would you like to submit a PR to change the name for v0.5.1? We can throw `DeprecationWarning ` if wiki_multilingual/wiki_cn is used by the user. We also need to make sure all test case/tutorial/conversion script/finetunining script do not use the old name.

**Comment by kenjewu** [comment]
OK. In addition to renaming these two data, do we still need to update the serialization file of the vocab corresponding to the some dataset ? @eric-haibin-lin  Currently，
```python
_vocab_sha1 = {'wikitext-2': 'be36dc5238c2e7d69720881647ab72eb506d0131',
               'gbw': 'ebb1a287ca14d8fa6f167c3a779e5e7ed63ac69f',
               'WMT2014_src': '230ebb817b1d86950d71e2e765f192a4e4f34415',
               'WMT2014_tgt': '230ebb817b1d86950d71e2e765f192a4e4f34415',
               'book_corpus_wiki_en_cased': '2d62af22535ed51f35cc8e2abb607723c89c2636',
               'book_corpus_wiki_en_uncased': 'a66073971aa0b1a262453fe51342e57166a8abcf',
               'wiki_multilingual_cased': '71bb9e248dc75dce9227d3c8c16fde3993588b9e',
               'wiki_cn': 'a1e06f8e39ae51ab8a92b8458e6a658b8b1f72bf',
               'wiki_multilingual': '2b2514cc539047b9179e9d98a4e68c36db05c97a'}
```
The corresponding objects of ` wiki_multilingual_cased ` and ` wiki_cn ` seem to be ` Vocab `, however  ` book_corpus_wiki_en_cased `, ` book_corpus_wiki_en_uncased ` and  ` wiki_multilingual ` corresponds to ` BERTVocab `.

**Comment by eric-haibin-lin** [comment]
I didn't realize wiki_multilingual_cased and wiki_cn are using the Vocab class. Is there any specific reason why they were kept Vocab is the previous PR? If not we should change it to BERTVocab.
Also on second thought `DeprecationWarning` is too much interruption, `warnings.warn` should be sufficient

**Comment by kenjewu** [comment]
@eric-haibin-lin I am sorry that I am confused. When I updated the Vocab file to BERTVocab, I only made ` book_corpus_wiki_en_cased `, ` book_corpus_wiki_en_uncased ` and ` wiki_multilingual `, so I thought the other two were Vocab. I just tested it and found that they are already BERTVocab.
 Now, I will start this issue.

**Comment by eric-haibin-lin** [comment]
Merged
