### ISSUE TITLE
Autobuild fails with Pygments lexer name '{.python .input}' is not known

### ISSUE THREAD

**Issue by Ishitori** [dmlc/gluon-nlp#557]
Sometimes during autobuild the build fails on the target `html` with a message `Pygments lexer name '{.python .input}' is not known`. 

Last time I have it when working on BERT, and the failure happened in a totally unrelated tutorial: `docs/examples/language_model/language_model.md:47`. Here is the pipeline: http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-548/5/pipeline/

Forcing build helps to fix that, but @eric-haibin-lin mentioned that this issue happens from time to time, and it would be nice to find the root cause of it.

**Comment by szha** [comment]
It usually happens when there are other failures, and it seems to be the case here too http://ci.mxnet.io/blue/organizations/jenkins/gluon-nlp/detail/PR-548/5/pipeline/#step-44-log-1531

What might be happening is that when rendering of a notebook failed, the make process skips the execution of the rest of the notebooks, and continues to the next sphinx build step. This results in sphinx trying to render notebooks that haven't been run.

**Comment by szha** [comment]
I will try to make it fail fast and give informative errors.

**Comment by szha** [comment]
Tracked in #559
