### ISSUE TITLE
Port ClinicalBERT to GluonNLP

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/gluon-nlp#709]
https://github.com/kexinhuang12345/clinicalBERT 
https://arxiv.org/abs/1904.05342

**Comment by leezu** [comment]
ClinicalBERT depends on the BERTClassification Block that currently resides in the Scripts folder:https://github.com/dmlc/gluon-nlp/blob/1e50a6606c5215e0dc28d016bb5f57bd668f47af/scripts/bert/model/classification.py#L76-L95

@eric-haibin-lin Any qualms about "stabilizing" that Block, ie. moving it to the main API so that the ClinicalBERT model can be provided via S3 from stable API? Or should we provide the ClinicalBERT model for now only from within scripts folder?

**Comment by leezu** [comment]
Main, pretrained model added by #735
We may want to add the fine tuned classification layer parameters in future.

**Comment by szha** [comment]
@leezu thanks for adding the model. For the last classification layer, let's handle it when such request arises.
