### ISSUE TITLE
KeyError: '<pad>' if run /scripts/word_embeddings/evaluate_pretrained.py with flag `analog-max-vocab-size`

### ISSUE THREAD

**Issue by liusy182** [dmlc/gluon-nlp#905]
## Description

run `/scripts/word_embeddings/evaluate_pretrained.py` with flag `analog-max-vocab-size` throws exception.

### Error Message
```
Traceback (most recent call last):
  File "evaluate_pretrained.py", line 216, in <module>
    vocab.set_embedding(token_embedding_)
  File "/Users/siyuanl/private/gluon-nlp/src/gluonnlp/vocab/vocab.py", line 412, in set_embedding
    new_idx_to_vec[1:, col_start:col_end] = embs[self._idx_to_token[1:]]
  File "/Users/siyuanl/private/gluon-nlp/src/gluonnlp/embedding/token_embedding.py", line 637, in __getitem__
    indices = [self._token_to_idx[token] for token in tokens]
  File "/Users/siyuanl/private/gluon-nlp/src/gluonnlp/embedding/token_embedding.py", line 637, in <listcomp>
    indices = [self._token_to_idx[token] for token in tokens]
KeyError: '<pad>'
```

## To Reproduce

```
cd scripts/word_embeddings

python evaluate_pretrained.py --gpu 0  --embedding-name glove --embedding-source glove.42B.300d --logdir results --analogy-max-vocab-size 300000 --analogy-datasets GoogleAnalogyTestSet BiggerAnalogyTestSet
```

## What have you tried to solve it?

It looks like the reason is because [enforce_max_size](https://github.com/dmlc/gluon-nlp/blob/master/scripts/word_embeddings/evaluate_pretrained.py#L208) trims off certain tokens such as `<pad>` which results to the error above.

What should be the correct way to run this script?

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by leezu** [comment]
Thanks for reporting this issue liusy182. The reason was that `enforce_max_size` function incorrectly overwrote an internal TokenEmbedding datastructure, breaking the use of `unknown_token`'s embedding for '<pad>'. When this script was written, modifying TokenEmbedding's internals was required. Based on https://github.com/dmlc/gluon-nlp/pull/750 we can now use proper API to make the required changes.

In general however, `vocab = nlp.Vocab(nlp.data.count_tokens(tokens))` can be replaced with vocab = `nlp.Vocab(nlp.data.count_tokens(tokens), unknown_token=token_embedding_.unknown_token, padding_token=None, bos_token=None, eos_token=None)`. I'm opening a PR for these two changes.

Unfortunately this error slipped through the tests. I'm also extending the testcase.
