### ISSUE TITLE
Consider providing a BERT weight download link?

### ISSUE THREAD

**Issue by fierceX** [dmlc/gluon-nlp#990]
Now the BERT weight is downloaded via gluonnlp, but in some cases the network may not be too good or the server does not have an external network. This requires running gluonnlp to download the BERT weight, which is a bit inconvenient, can provide a BERT weight download link, or more Multiple models and dataset download pages, you can download the required weights and datasets without running gluonnlp
@dmlc/gluon-nlp-team 

## References
- list reference and related literature
- list known implementations

**Comment by szha** [comment]
The current code should still work in the described scenario because:
- The model download logic avoids repeatedly downloading the model by checking the checksum of the model weight file at target location.
- By specifying `root` argument in `get_model`, you can auto-download the model parameters into a location of your choosing.

**Comment by fierceX** [comment]
@szha 
I know how it works now. I mean, on some servers that don't have an external network, it's a little unfriendly, mainly because you can't download weight files directly from a web page. 
This requires running the code downloading weight file repeatedly on a machine with a network.

**Comment by seeris** [comment]
download links would allow to  use gluon-nlp models with other languages e.g. clojure/scala

**Comment by seeris** [comment]
ok, _a_ solution: 
- https://gluon-nlp.mxnet.io/model_zoo/bert/index.html provides an example
```python
import gluonnlp as nlp; import mxnet as mx;
model, vocab = nlp.model.get_model('bert_12_768_12', dataset_name='book_corpus_wiki_en_uncased', use_classifier=False, use_decoder=False);
tokenizer = nlp.data.BERTTokenizer(vocab, lower=True);
transform = nlp.data.BERTSentenceTransform(tokenizer, max_seq_length=512, pair=False, pad=False);
sample = transform(['Hello world!']);
words, valid_len, segments = mx.nd.array([sample[0]]), mx.nd.array([sample[1]]), mx.nd.array([sample[2]]);
seq_encoding, cls_encoding = model(words, segments, valid_len);
```
- create a script, e.g. `bert.py` with the code from above 
- install dependencies and run
```shell
# install dependencies
sudo apt-get update
sudo apt-get install -y python3 python3-pip
pip3 install gluonnlp mxnet # not sure wether 'sudo' is needed

# run the script
python3 bert.py
```
- the BERT model will be downloaded to `~/.mxnet/models`
    - for example `/root/.mxnet/models` or `/home/user/mxnet/models`
    - files
         - bert_12_768_12_book_corpus_wiki_en_uncased-75cc780f.params
         - book_corpus_wiki_en_uncased-a6607397.vocab

it is obvious, of course. nevertheless..

**Comment by eric-haibin-lin** [comment]
So the use case is about easier ways to download / distribute model weights without setting up gluon-nlp? That sounds reasonable. 

Adding links to those parameter weight on the website is not hard. We need exact effort to maintain the documentation everytime the link changes but since model weight does not change frequently, it should be fine. @szha maybe we should include the link in the upcoming model catalog page?

**Comment by eric-haibin-lin** [comment]
will track the issue in https://github.com/dmlc/gluon-nlp/issues/990
